Chore: Added free web book alt to StatLearning
ossu/data-science pull request #125
Opened 2024-05-18 22:45 UTC by Smcgb

In RFC 118, the alternate link mentioned for the free textbook course version was left off.

2024-05-19 03:20 UTC, pulkitkrishna00 requested changes
I don't think mentioning the resources for R version of the textbook as an alternative of the python version of the course makes sense. It would be make much more sense to link to the python version of the textbook and its resources instead.

2024-05-19 03:20 UTC, pulkitkrishna00 commented on README.md
> +[Statistical Learning with Python by Stanford University on EdX](https://www.edx.org/learn/data-analysis-statistics/stanford-university-statistical-learning-with-python) ([Alt](https://www.statlearni
[Statistical Learning with Python by Stanford University on EdX](https://www.edx.org/learn/data-analysis-statistics/stanford-university-statistical-learning-with-python) ([Alt](https://www.statlearning.com/resources-python)) or [Statistical Learning With R by Stanford University on EdX](https://www.edx.org/learn/statistics/stanford-university-statistical-learning) ([Textbook](https://hastie.su.domains/ISLP/ISLP_website.pdf.download.html), [Textbook resources](https://www.statlearning.com/resources-python))

2024-05-19 14:06 UTC, Smcgb commented
The link to the resources also contains the jupyter notebook, python and R files so it can be used as a complete course.

I think either way these are good ways to show the alternatives ways to approach the course.

2024-08-11 14:58 UTC, Smcgb commented
Checking in on this request for merge, accepted @pulkitkrishna00 change.

2024-08-11 17:29 UTC, waciumawanjohi commented
Thanks for the PR and the followup!

2024-08-11 17:29 UTC, merged